### ISSUE TITLE
Running spot() on new compromise nlp version

### ISSUE THREAD

**Issue by orzilca** [nlp-compromise/nlp_compromise#107]
Hi,

What is the alternative for spot from the old version? (1.x)

I was using spot to analyze texts, it looks like it does not exist in the current version..

**Comment by spencermountain** [comment]
ah, hi Or, yeah sorry I didn't document that very well.
I back-pedelled a bit on a generic NER method, just because it's not always agreed-upon what should be pulled-out. Fortunately, all the specific functionality is there, and it shouldn't be too hard to cherry-pick what you'd like.
```
nlp.text('').people()
nlp.text('').organizations()
nlp.text('').places()
```
alternatively you could just loop through the terms and grab what you'd like.
the `spot` method basically just grabbed every capitalized term that wasn't the first term. you could reproduce that with `term.is_capital()`
cheers

**Comment by yossi-zlot** [comment]
Do you mean that non capitalized nouns will not be picked by spot?
Is there a method that picks up nouns in a way that they are gathered together into expression if there are few in succession?
Thanks

**Comment by spencermountain** [comment]
yeah, the lumping/chunking of terms is already done. I forget the details of `spot`, but it wasn't super-fancy. If you know what you're specifically looking for, you can just loop through the terms and look at `term.pos`, and `term.is_capital()`. Now that we known `pos['Person']`, and `pos['Location']`, you're well-ahead of what the spot() method could do.

**Comment by spencermountain** [comment]
i don't know what your project use-case is, but grabbing person, location, and place is probably gonna do the trick. I could wrap that up in a method called spot if you wanted, but it would be a bit redundant
cheers

**Comment by spencermountain** [comment]
yeah, i'm gonna do that. It make sense. Gimme a couple minutes

**Comment by yossi-zlot** [comment]
Thanks - I can do without but its easier this way!
:) :) :)

**Comment by spencermountain** [comment]
```javascript
let str="Oo-ee-oo I look just like Buddy Holly. Oh-oh, and you're Mary Tyler Moore"
nlp.text(str).topics()
// [ { count: 1, text: 'mary tyler moore' },
//   { count: 1, text: 'buddy holly' }
// ]
```

https://gist.github.com/spencermountain/1f589b4c9798bab2907b26d9d8b6b6af

v4.9.0, please check it out.
:metal:
