### ISSUE TITLE
Person name fields inappropriately lower cased

### ISSUE THREAD

**Issue by pags** [nlp-compromise/nlp_compromise#206]
Version: 6.1.2
```
var nlp = require('nlp_compromise');

console.log(nlp.text('Ronald McDonald').people());
```

```

[ Person {
    whitespace: { preceding: '', trailing: '' },
    text: 'Ronald McDonald',
    normal: 'ronald mcdonald',
    expansion: null,
    reason: 'is_person',
    pos: { Noun: true, Person: true },
    tag: 'Person',
    honourific: null,
    firstName: 'ronald',
    middleName: '',
    lastName: 'mcdonald' } ]
```

I have no way to get the last name with correct capitalization.

**Comment by spencermountain** [comment]
ah, hmm. That's a good point.
And it would be incorrect to shoe-horn it into titlecase - mcdonald is a perfect example.
this is a little tricky, but should be done. I've got a busy two weeks, but will do it after. 
thanks!

**Comment by ilyankou** [comment]
I'm currently working on it – will be completed today/tomorrow.

I'm trying to improve name parser, too, because now for double surnames such as `Williams-Johnson` it tags `Williams` as `middleName`, and for double first names like `Mary-Ann` it puts `Ann` into `middleName`, which is (in my opinion) incorrect.

**Comment by pags** [comment]
Appreciate it, love the library.
